api: https://polynetworkcc3dcb2-5-api.dev.z7a.xyz
zil_start_height: 38
zil_monitor_interval: 40
corss_chain_manager_address: zil16vxy2u59sct5nupryxm3wfgteuhve9p0hp605f
poly_wallet_file: wallet.dat
poly_wallet_pwd: dummy