zil_config:
  zil_api: https://polynetworkcc3dcb2-5-api.dev.z7a.xyz
  zil_chain_id: 333
  zil_message_version: 1
  zil_start_height: 38
  zil_monitor_interval: 40
  corss_chain_manager_address: zil16vxy2u59sct5nupryxm3wfgteuhve9p0hp605f
  side_chain_id: 1
  key_store_path: keystore
  key_store_pwd_set:
    7d48043742a1103042d327111746531ca26be9be: "xiaohuo"
    de0a0fbe9042aa165fb21e7b5e648162bcf1e8e7: "xiaohuo"
poly_config:
  poly_wallet_file: wallet.dat
  poly_wallet_pwd: dummy
  poly_monitor_interval: 40
  entrance_contract_address: "0300000000000000000000000000000000000000"
  rest_url: http://beta1.poly.network